### ISSUE TITLE
render to pdf issues

### ISSUE THREAD

**Issue by thartbm** [jennybc/happy-git-with-r#117]
Not sure this is relevant, but when rendering to pdf for our lab, I found that three links prevent this. These links have a UTF character that can be removed from the link (as far as I can see they still work), and they include a colon. I could not find a way to include colons and keep the link clickable. The workaround I found was to include the link as a bash chunk, and let people copy paste them. Not great. But then again, this might not be a problem worth solving as the other render formats do work great.

**Comment by thartbm** [comment]
Oh, the links are in chapter 36, the last two, and one in chapter 38, in a section that's also on using github search options.

**Comment by jennybc** [comment]
Oh wow, I've never attempted to render this to pdf.

Can you provide specific links to the guilty lines in the source `.Rmd` files?

Here's how:

https://stackoverflow.com/questions/23821235/how-to-link-to-specific-line-number-on-github

**Comment by jennybc** [comment]
What if you remove `&utf8=✓` from the affecteded links? I've done that in a branch and pull request:

#125

Can you either attempt to build the PDF version from that branch or make the same edits locally by hand and see if it's fixed? (one of the links is redundant with the others and can just be deleted)

**Comment by thartbm** [comment]
Sorry, IIRC that needs to be done too, but doesn't break the links. However, I will test on the new branch as soon as I can, and report. Thanks!

**Comment by jennybc** [comment]
> OK great: that works for me! What magic did you do? Maybe I had to clean up some intermediate LaTeX files or md files before trying again?

I just deleted `&utf8=✓` from the links. I think we can dispense with it, given our specific searches.

> there is another line that prevents the render if the whole project is not a git repo

OK I've prevented the execution of that specific line for now.

I'm going to merge.
