### ISSUE TITLE
compile problem: bash chunks don't work on vanilla windows

### ISSUE THREAD

**Issue by maxheld83** [jennybc/happy-git-with-r#120]
This is an issue with *compiling* the bookdown, *not* with the instructions themselves.
We were trying to make some additions to the book as a PR. 
Some of us were using windows, and these users could not compile the book from master as is.

In three places, the (fantastic) book contains rmarkdown bash chunks, like so:

```{bash collapse = TRUE}
which git
```

(These are, of course distinct from the chunks which are non-evaluated, and merely list bash for syntax highlighting like so:

``` bash
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

The above to-be-evaluated bash chunks appear to fail for us (cc @mkkkt and @aDeLe24, both on Windows) (see error message below). 
The chunks *do* appear to work on Windows machines with the Windows Subsystem for Linux installed (cc @Elen93), though this a small-n observation 🐱 

I understand that *actually* the bash used *does* work even in the *Windows* git bash, but I am guessing that knitr still won't evaluate it, because it, well, doesn't have the *real* bash available.

This is in line with the [bookdown documentation](https://bookdown.org/yihui/rmarkdown/language-engines.html#shell-scripts) that says on the matter:

> You can also write Shell scripts in R Markdown, if your system can run them (the executable bash or sh should exist). Usually this is not a problem for Linux or macOS users. It is not impossible for Windows users to run Shell scripts, but you will have to install additional software (such as Cygwin or the Linux Subsystem).

So our hypothesis is that these 3 offending chunks will always fail on Windows, unless the WSL or some other fancy stuff is installed.
Correct?

(We're going to put up a PR which conditionally disables these chunks on Windows in a sec).

**Comment by maxheld83** [comment]
@mkkkt could you paste your error message in here from *with* using the offending chunks? (one would do). It'd just be nice to have the actual error message in here. Being on macOS I can't reproduce it.

**Comment by aDeLe24** [comment]
This is on Windows 10 without the WSL. 
 
```
processing file: git-remotes.Rmd
running: bash  -c "git remote -v"
Quitting from lines 13-14 (git-remotes.Rmd) 
Fehler in system2(cmd, code, stdout = TRUE, stderr = TRUE, env = options$engine.env) : 
  '"bash"' not found
Ruft auf: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Ausf�hrung angehalten
Fehler in Rscript_render(f, render_args, render_meta) : 
  Failed to compile git-remotes.Rmd
Ruft auf: <Anonymous> ... render_book -> render_new_session -> Rscript_render
Ausf�hrung angehalten

Exited with status 1.
```

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200) 

Matrix products: default  locale: 
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    
[5] LC_TIME=German_Germany.1252     

attached base packages: 
[1] stats     graphics  grDevices utils     datasets  methods   base       

loaded via a namespace (and not attached):  
[1] compiler_3.5.1  bookdown_0.9    htmltools_0.3.6 tools_3.5.1     yaml_2.2.0       
[6] Rcpp_1.0.0      rmarkdown_1.11  knitr_1.21      xfun_0.4        digest_0.6.18   
[11] evaluate_0.12
```

**Comment by jennybc** [comment]
Ah, interesting. I had never thought about this. Yes I am happy to make it possible for Windows user to successfully build the book. I'll make some additional comments on the PR.
