### ISSUE TITLE
Check for appropriate links to appendix re: the shell

### ISSUE THREAD

**Issue by jennybc** [jennybc/happy-git-with-r#127]
Now that #123 is merged, this task remains:

  * Check that this shell appendix material is cross-referenced consistently from elsewhere in the book. By this, I mean rationalizing the link text and method. See https://bookdown.org/yihui/bookdown/cross-references.html.
  * Check that we link to it everywhere it might be useful. Search for "terminal" or "shell" in the text. Should there be a link to the appendix?

**Comment by william3031** [comment]
Something like this? https://github.com/jennybc/happy-git-with-r/pull/153
