### ISSUE TITLE
Revise treatment of GitHub Desktop client

### ISSUE THREAD

**Issue by jennybc** [jennybc/happy-git-with-r#136]
Looks like it may be time to revisit our negativity re: GitHub's Desktop client.

From a [twitter conversation](
https://twitter.com/billygriffin22/status/1104097810679361536) with @billygriffin:

> Thank you! The two issues you mentioned are both no longer things in the latest version. The button formerly known as "Sync" now displays Fetch/Pull/Push depending on the state, and we ask that users use Git for Windows as it's become a more supported project.

**Comment by billygriffin** [comment]
Thanks @jennybc! If you have any questions or feedback along the way, the repo is open source at https://github.com/desktop/desktop and you're also more than welcome to reach out to me directly. 😄 

The tension between ease of use for beginners and exposing core Git concepts is definitely one we constantly feel, so feedback on how you think we've either hit or missed the mark is really appreciated.

**Comment by billygriffin** [comment]
Hi @jennybc! As an update, we shipped [GitHub Desktop 2.0](https://github.blog/2019-06-05-github-desktop-expands-to-support-stashing-and-rebasing/) yesterday. I would love your thoughts if you have a chance to take a look! 

Also, would you be open to me opening a PR for this to provide some initial verbiage, and obviously you're free to update it however you'd like prior to merging - figured that might make your life easier. I just want to make sure the things people are arriving on as they're picking up Git (especially in communities with newer folks to version control) are accurate. Let me know! 😄

**Comment by jennybc** [comment]
Thanks, I saw that announcement! I'm teaching Git next week, so maybe I'll hear some info from people using GitHub Desktop.

Sure, I'd be happy for a PR with new verbiage. I might refine it, but I'm certainly not clinging to my negative thoughts and am happy to declare that the client has improved since I personally used it.
