### ISSUE TITLE
unhappy git and rstudio when files on server

### ISSUE THREAD

**Issue by jessicawalsh1** [jennybc/happy-git-with-r#151]
Hi, thanks for your excellent help guide for getting git to talk to Rstudio! However, I spent 4 hours trying to get git to talk to Rstudio and realised that the error I was encountering was not covered in your help troubleshooting documentation. Git was talking with online GitHub repos via terminal. Rstudio git path in global options was fine. However, when I tried to make a new R project with git repo, a fatal error occurred ("Incorrect function"), r studio aborted and crashed. On reopening Rstudio, the R project was created, but not with a git repo. I figured out it was because I was trying to put the project on my university's remote server (where all my other files are) rather than on my computer's hard drive. The Rprojects and git work fine when placed on hard drive. I couldn't find any other help/suggestions related to this issue. 

It seems to be an error/bug in the Rstudio 'create project as a subdirectory of' '~/'. It doesn't like being directed to a remote location. Any thoughts? 

All most recent versions of Rstudio, R and git.
R version 3.6.0 (2019-04-26) 
Platform: x86_64-w64-mingw32/x64 (64-bit)
Rstudio: Version 1.2.5001
git version 2.23.0.windows.1

**Comment by jennybc** [comment]
I guess I'd say this is a variant of the problems described here:

https://happygitwithr.com/troubleshooting.html#rstudio-is-not-making-certain-files-available-for-stagingcommitting

> Is your Git repo / RStudio Project inside a folder that … eventually rolls up to Google Drive, DropBox, Microsoft OneDrive, or a network drive? If yes, I recommend you move the repo / Project into a plain old directory that lives directly on your computer and that is not managed by, e.g., Google Drive.
>
> If you cannot deal with the two root causes identified above, then it is possible that a more powerful Git client (chapter 8) will be able to cope with these situations. But I make no promises. You should also try Git operations from the command line.

**Comment by jennybc** [comment]
Possible related to these existing RStudio issues:

https://github.com/rstudio/rstudio/issues/3105

https://github.com/rstudio/rstudio/issues/4137

**Comment by jennybc** [comment]
I'm not hearing any pain around this these days and it looks like the RStudio issues have been addressed, so closing.
