### ISSUE TITLE
Suggestion for bullet point for GitHub username

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [jennybc/happy-git-with-r#152]
I regularly use the Username advice section at https://happygitwithr.com/github-acct.html with students / new GitHub users, and I'd like to make a suggestion for a new bullet point: Avoid using uppercase letters. GitHub names are case insensitive (e.g. https://github.com/MINE-CETINKAYA-RUNDEL goes to https://github.com/mine-cetinkaya-rundel anyway) but upper/lower case letters sometimes make it tricky to match manually-entered GitHub name data (e.g. from a student survey) to data pulled from GitHub. I don't see a compelling reason to use uppercase letters in usernames. I would only make this a suggestion (avoid using...) as opposed to a rule (don't use...) but I think it would help new learners who might be unaware of case insensitivity anyway. Happy to make a PR if you think this is a good idea.

**Comment by jennybc** [comment]
I'm happy to gain some short advice about this, i.e. that it's unwise and sort of pointless to do anything clever with casing. Recommend all lowercase.

But I also think you'll probably always need to make your matching robust to this. I remember this repetitive headache every fall with STAT 545, trying to reconcile who UBC said was in my class and info provided directly from students, e.g. their GitHub usernames. So much chaos from typos, different notions of first/middle/last names, people dropping/adding, etc 🤪

**Comment by mine-cetinkaya-rundel** [comment]
That second paragraph summarizes my first couple weeks of class every semester. It's hell! And my code seems to be always just a tad less robust than it needs to be...

I will address this issue with a PR in the next couple days, thanks!
