### ISSUE TITLE
Personal active token

### ISSUE THREAD

**Issue by jisidrosanchez** [jennybc/happy-git-with-r#161]
Hi there,
Trying to follow the workshop https://happygitwithr.com/workshops.html and when I am trying to create "Create and save a GitHub Personal Access Token (PAT)". I have the following issue.

Creating the token is fine, but when I do have to copy the token into Renviron. using usethis::edit_r_environ() from Studio I get this error. 

Error: [EACCES] Failed to open '/Users/jis/.Renviron': permission denied

I did all the previous steps from the website but I cannot move from here. I didn't do the set up SSH keys but I don't think I need it for this. Myrepo is on /Users/jis/Github but I don't think that is an issue (different directory). I need permissions. any help?
Thanks,

**Comment by jennybc** [comment]
It's very peculiar to not have permission to edit `.Renviron` in your home directory.

From where I sit, I can't tell if it's an issue with your permissions on this directory or something special about `/Users/jis/.Renviron`. But that is my suggested line of troubleshooting: figure out why you don't seem able to edit a dot file in your own home directory.

**Comment by jisidrosanchez** [comment]
I appreciate your answer. I have tried the troubleshooting too. Maybe the solution is to have a clean environment in Mac. Catalina might have done something with the OS. Thanks Jenny for the help.

**Comment by jennybc** [comment]
Oh, hmmm. Yeah, this is an especially weird situation on a personal macOS system.
