### ISSUE TITLE
Git Hell for Windows Idea: ‘fatal: repository not found’

### ISSUE THREAD

**Issue by sgoldman-de** [jennybc/happy-git-with-r#162]
Great book, though sadly I only refer to it when I'm in trouble. 

This might be beyond the scope of this book, but knowing that there are some wonky Windows-specific frustrations mentioned, I figured I'd add: 

When trying to clone an existing github repo within RStudio, I was getting the fatal: repository not found’ error, and the issue turned out that Windows Credential Manager had stored an old version of my GitHub password.

**Comment by jennybc** [comment]
This is basically #173. The TL;DR is that I've done a lot of updates re: creds and hopefully the people suffering from this will see that going into their OS-level credential store is one of the troubleshooting strategies.

`usethis::git_sitrep()` and `usethis::gh_token_help()` are also better now in terms of helping people figure out this problem.
