### ISSUE TITLE
Consolidate the GitHub PAT info

### ISSUE THREAD

**Issue by jennybc** [jennybc/happy-git-with-r#168]
Currently it exists in (at least) these places:

  * An appendix: <https://happygitwithr.com/github-pat.html#github-pat>
  * The chapter about caching HTTPS credentials: <https://happygitwithr.com/credential-caching.html>

**Comment by jtr13** [comment]
On this topic: https://happygitwithr.com/github-pat.html#github-api implies that a GITHUB_PAT is required to use `devtools::install_github()` from any repo, but this https://www.rdocumentation.org/packages/devtools/versions/1.13.6/topics/install_github specifies that it is only required for private repos.

**Comment by jennybc** [comment]
The general need for a PAT with `devtools::install_github()` (which is really `remotes::install_github()`, under the hood) is because there are very strict limits on the number of GitHub API calls when you don't send a PAT. Even if you are installing from public repos, you will want a PAT if you use `install_github()` with any regularity.

Yes, a PAT is absolutely required for private repos. But in practice, it also ends up being a *de facto* requirement for non-trivial work with public repos.

It's hard to say which usethis functions require a PAT. Some absolutely require it but many can perhaps do some/most of their job without it. But usethis v2.0.0 should be very clear when lack of PAT is a problem. I think any usethis user who uses the Git/GitHub functionality should configure a PAT.

**Comment by jtr13** [comment]
Oh interesting, didn't realize it wasn't quite an either/or situation. My main concern is not asking (some types of) students to do anything more than necessary, for example when installing a package from GitHub.

By the way, if I can be of any assistance in updating / expanding _Happy Git_ let me know. I'll have some time in December/January (no trips planned...) If I'm pointed in the right direction I can draft material, or test drive new sections.
