### ISSUE TITLE
browse_github_token misspelled?

### ISSUE THREAD

**Issue by hugotseixas** [jennybc/happy-git-with-r#170]
I'm not sure if this is the right place for this, but it seems that the {usethis} function in section "10.1.2 How to get a PAT?" is misspelled as "usethis::create_github_token". The function I found to access the url to create the PAT is "usethis::browse_github_token".

**Comment by jennybc** [comment]
This function is renamed in the soon-to-be-released usethis v2.0.0. Old name was `browse_github_token()`, new name is `create_github_token()`.
