### ISSUE TITLE
Ch 16: Existing project, GitHub first -- Not able to use Rstudio interface

### ISSUE THREAD

**Issue by aanders8** [jennybc/happy-git-with-r#172]
Greetings Jenny,

Thank you for the great resource. I wanted to share a solution to a problem I ran into while trying to implement this chapter. Please excuse my unfamiliarity with some of the lingo. I had a project that was about 30mb on my PC that I wanted to move to a Github repository  -- a blogdown website. When I got to "16.4 Stage and commit", rstudio started not functioning very well. I opened the git pane and tried selecting the various files, but the pane was nonresponsive. The window that pops up after clicking on the "commit" button at the top of the git pane was also non-responsive. I updated rstudio and all my packages, restarted the software and PC, etc., and was not having any luck. 

I tried going the route of putting all the files directly on github.com and then pulling them to the local repository, but Github.com has a limit on drag-and-drop uploading (100 files?). So after scrounging around I found this: https://stackoverflow.com/questions/43690977/commit-a-large-number-of-files-in-rstudio-using-git-panel

As described in that post, opening up the shell and putting in `git add -A && git commit -m 'staging all files'` took care of the issue.

Not sure if this is something worth adding to the book for other readers, but it was a very helpful solution for me.

Thank you,
Austen

**Comment by jennybc** [comment]
Ouch! I see the problem and it sounds like you found a good solution. It's a constant challenge to keep the introductory workflows "complete, for most people", but also to anticipate common obstacles. At this point, I think this affects a relatively small subpopulation and the poor souls who suffer will hopefully search and find the solution, as you did. This thread will help make those searches more fruitful! But until I hear of this happening more often, I'm not ready to add to the main text.
