### ISSUE TITLE
Another room in hell

### ISSUE THREAD

**Issue by jtr13** [jennybc/happy-git-with-r#173]
Since I've seen this twice in two days, I thought I'd open an issue. I believe it's another variant of a push fail at the RStudio level https://happygitwithr.com/troubleshooting.html#push-fail-at-the-rstudio-level

```
Remote: Permission to currentname/repo.git denied to oldacctname fatal: unable to access 
'https://github.com/currentname/repo.git/': The requested URL returned error: 403
```

The cause is another (old) GitHub account: following the instructions to introduce yourself to Git does not remove stored credentials from abandoned accounts. We were able to solve the problem quickly by following the instructions here:

Mac: delete git entries in Keychain Access:
https://stackoverflow.com/a/31005094/5314416

Windows: delete git generic credentials in Credential Manager:
https://stackoverflow.com/a/40907049/5314416

**Comment by jennybc** [comment]
This is basically the sort of credential inspection and cleaning that I'm alluding to here:

https://happygitwithr.com/credential-caching.html#access-the-os-level-keychain-or-wallet

But obviously that's sort of subtle and not terribly prescriptive.

**Comment by jtr13** [comment]
In these particular cases, the students were not able to push and it was clear from the error messages that some connection with the old account was the cause but it wasn't clear how to clear the debris.  Apparently they're very quick to create new accounts which comes back to bite them.

**Comment by jennybc** [comment]
Yeah, I don't feel comfortable telling people to nuke their Git credential store, in general. So on macOS and Windows, yes, this means deleting a whole set of specific creds from keychain or credential manager.

But there are many people who would benefit from that, for sure. The trick is identifying them.

**Comment by jennybc** [comment]
I feel like the root cause here is lack of account and password hygiene, i.e. not having a system to manage secrets and, therefore, creating new accounts or tokens willy-nilly, to get unstuck, because it solves an immediate problem (but then creates many more downstream problems).

**Comment by jtr13** [comment]
Yes, exactly!

**Comment by jennybc** [comment]
I've reread this and have recently done lots of update. I do mention going into the OS-managed credential store in <https://happygitwithr.com/https-pat.html#pat-troubleshooting>

> On Windows, your Git credentials are probably being stored via Credential Manager.
> 
> On macOS, your Git credentials are probably being stored in the Keychain.
> 
> If you really want to poke around directly to explore or clean out your GitHub credentials, launch Credential Manager (Windows) or Keychain Access (macOS) and search for “github.com”.

For now, I feel at peace with this at least raising the possibility, but without sending too many people barking up this tree. If I hear of lots of people who need to do this, we can reconsider how prominently to feature this.
