### ISSUE TITLE
More help with weird git installs

### ISSUE THREAD

**Issue by AmeliaMN** [jennybc/happy-git-with-r#194]
I am the biggest fan of happygitwithR. It's the best. It has saved me and my students hundreds of hours of frustration. But somehow, I have found myself in a situation not described in the book. It is on Windows (duh) on the computers we have in my building. The IT folks have installed git and it's obviously not one of your preferred methods. But, I can 
- find the git.exe file
- set the path to that executable in my RStudio global options
- see git documentation if I type `git` in my RStudio terminal
- see "version control" as an option when I am making a new project

Unfortunately, I cannot
- use things in `gitcreds`, such as 

```
gitcreds::gitcreds_set()
Error in throw(new_error("gitcreds_nogit_error")) : 
  Could not find system git
```

I have restarted RStudio a million times (I don't want Jenny to have to stop the car for me!!) and even tried the "I’ve seen this help" from [chapter 13](https://happygitwithr.com/rstudio-see-git.html). No joy. Any other suggestions, or am I stuck trying to convince my IT folks to install git differently?

**Comment by jennybc** [comment]
I think this has become a gitcreds question and should probably become an issue there.

https://github.com/r-lib/gitcreds/issues

**Comment by AmeliaMN** [comment]
Thanks, I should have figured out that was a better place to ask.
