### ISSUE TITLE
HTTPS doesn't work anymore

### ISSUE THREAD

**Issue by nzgwynn** [jennybc/happy-git-with-r#201]
This should really be updated b/c I just connected to a project via https and of course it didn't work!  SSH is the only one that works now and I didn't realize that you need a new code for each computer!

**Comment by jennybc** [comment]
> HTTPS doesn't work anymore

This isn't the case, though. HTTPS is, if anything, the most recommended protocol. I only use HTTPS at the moment.

I think maybe you missed the transition to using personal access tokens (as opposed to username/password).

https://happygitwithr.com/https-pat.html
