### ISSUE TITLE
Link broken in '7.1.1 Configure the Git editor'

### ISSUE THREAD

**Issue by Henrik-P** [jennybc/happy-git-with-r#213]
The link in the last sentence 'many combinations of OS and editor'; http://swcarpentry.github.io/git-novice/02-setup/, is broken.

In addition, given that the guide is about R, and often about using git from within RStudio, wouldn't it be relevant to provide code for RStudio as default editor in the actual text as well, instead of "only" 'Substitute your preferred editor for "emacs" here'?

Cheers

**Comment by jennybc** [comment]
> The link in the last sentence 'many combinations of OS and editor'; http://swcarpentry.github.io/git-novice/02-setup/, is broken.

Can you tell what the intended link should be now?

> In addition, given that the guide is about R, and often about using git from within RStudio, wouldn't it be relevant to provide code for RStudio as default editor in the actual text as well, instead of "only" 'Substitute your preferred editor for "emacs" here'?

Last time I looked into this, I remember it was difficult (impossible?) or somehow not very functional. Has the world changed since then?

**Comment by Henrik-P** [comment]
>Can you tell what the intended link should be now?

https://swcarpentry.github.io/git-novice/02-setup.html

>Last time I looked into this, I remember it was difficult (impossible?) or somehow not very functional. Has the world changed since then?

I don't know.

Because GitKraken is among your [top recommended clients](`https://happygitwithr.com/git-client.html#recommended-git-clients`), perhaps add it in an example of `git config --global core.editor` in the section [7.1.1 Configure the Git editor](https://happygitwithr.com/hello-git.html#git-editor)?



Thanks for your great work with Happy Git!
