### ISSUE TITLE
Add YAML example to Render an R script tutorial

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [jennybc/happy-git-with-r#23]
On the [Render an R script tutorial](https://github.com/jennybc/happy-git-with-r/blob/master/31_usage-first-use-r-script-and-github.Rmd), it would be useful to include a sample YAML, a la [Render an R script](https://github.com/jennybc/happy-git-with-r/blob/master/30_usage-first-use-rmd-and-github.Rmd). It took me a few tries to get it right based on the written instructions -- likely because I read them out of order, but I'm sure I won't be the only one to fail at following instructions.

**Comment by jennybc** [comment]
Parking here for now

``` yaml
#' ---
#' title: "Something fascinating"
#' author: "Jenny Bryan"
#' date: "`r format(Sys.Date())`"
#' output:
#'   html_document:
#'     keep_md: TRUE
#' ---
```

Or

``` yaml
#' ---
#' title: "Something fascinating"
#' author: "Jenny Bryan"
#' date: "`r format(Sys.Date())`"
#' output: github_document
#' ---
```
