### ISSUE TITLE
use of git with students

### ISSUE THREAD

**Issue by graphdr** [jennybc/happy-git-with-r#24]
Jenny, we talked briefly about how you have students use github to share their homework with you. I'm hoping you could share your workflow on that. Thanks, Great workshop! 
--Richard

**Comment by vnijs** [comment]
@jennybc is your workflow similar to http://www.princeton.edu/~mjs3/soc504_s2015/submitting_homework.shtml ?

**Comment by jennybc** [comment]
I am now admitting that my "GitHub in the classroom" content has grown stale and, given that I'm no longer a prof, will only grow more stale. Luckily, others have picked up this banner. For example:

https://arxiv.org/abs/1811.02021

Using GitHub Classroom To Teach Statistics
Jacob Fiksel, Johanna S. Hardin, Leah R. Jager, Margaret A. Taub
(Submitted on 5 Nov 2018)

Git and GitHub are common tools for keeping track of multiple versions of data analytic content, which allow for more than one person to simultaneously work on a project. GitHub Classroom aims to provide a way for students to work on and submit their assignments via Git and GitHub, giving teachers an opportunity to teach these version control tools as part of their course. In the Fall 2017 semester, we implemented GitHub Classroom in two educational settings--an introductory computational statistics lab and a more advanced computational statistics course. We found many educational benefits of implementing GitHub Classroom, such as easily providing coding feedback during assignments and making students more confident in their ability to collaborate and use version control tools for future data science work. To encourage and ease the transition into using GitHub Classroom, we provide free and publicly available resources--both for students to begin using Git/GitHub and for teachers to use GitHub Classroom for their own courses.
