### ISSUE TITLE
notes on RStudio finding Git

### ISSUE THREAD

**Issue by jennybc** [jennybc/happy-git-with-r#25]
Taken by @kevinushey at the useR! tutorial.

New specific ways for RStudio to not find Git. I can mitigate these with changes to the instructions:

- [X] make sure to specify`git.exe` not `git-bash.exe` (windows)
- [ ] always install Xcode command line tools (mac)

1. Some Windows users choose the incorrect git executable (e.g. 'git-bash.exe' vs 'git.exe') and as a result git integration doesn't work. (I remember one case in the past where a user basically locked
themselves out of the IDE because they set the wrong git executable and RStudio's attempts to run it on startup froze the system).

1. OS X users can't use Git unless command line tools are installed, even if a custom version of Git is installed and pointed to by RStudio. Except for El Capitan, where this problem is not seen. Related to #8. (This will presumably get fixed in the IDE.)

**Comment by daattali** [comment]
@kevinushey is there a technical reason why git-bash is BAD and git.exe is GOOD? I find myself using git bash (not opened via rstudio) over the git shell that opens from rstudio. I was going to change the shell from rstudio to git-bash but then found this warning, so I'm wondering why?

**Comment by kevinushey** [comment]
If `git-bash.exe` is specified as the Git executable there, then effectively RStudio will hang when attempting to make its own background invocations of Git. This was leading to e.g. 'white screen of death' issues for users (RStudio calls Git on startup, and then gets stuck waiting for Git which never exits) so we wanted to ensure this couldn't happen.

**Comment by daattali** [comment]
Do we (we = you...) know why this is happening--is this a bug with rstudio or something expected because of the different between the two?

**Comment by kevinushey** [comment]
I don't exactly know why; I suspect it's because `git-bash.exe` expects to be launched interactively (with input fed in from the user) rather than programmatically; when invoked in a programmatic way it leaves an (invisible) window open that never closes.

**Comment by daattali** [comment]
Fair enough. I'll keep invoking git bash separately from rstudio then. Thanks!
