### ISSUE TITLE
collecting and reviewing student pull requests

### ISSUE THREAD

**Issue by vnijs** [jennybc/happy-git-with-r#28]
@jennybc Thanks for providing these excellent materials! 

Similar to @graphdr I'm curious how you use git and github (or gitlab) for class. Together with @sanjiverat I have been working on an Rstudio addin to make it a bit easier for students (and faculty) to get started with git and gitlab (see https://github.com/vnijs/gitgadget). The main thing we are still working on is how to best collect and review student pull requests. We plan to create all student accounts in advance and will use the gitlab API to create pull requests on the assignment due date.

@jennybc @daattali What is the most practical approach to review all student pull requests and provide feedback?

**Comment by daattali** [comment]
Are these pull requests that you *expect* students to make, eg from an assignment?  In STAT545 we don't really use PRs with the students too heavily (at least not previously, I'm not sure if @jennybc is planning to change that)

**Comment by vnijs** [comment]
Yes. When faculty push assignments to a class repo they are forked for all students/teams using the gitlab API. The plan is to also use the API to create pull request for students/teams on the due date.

@daattali If you don't use PRs then how do you review student's work and provide feedback?

**Comment by daattali** [comment]
In the past 2 years, the workflow has been:
- each student has their own repo
- all assignments of a students are inside that repo
- to submit an assignment, they open an issue entitled "Please mark assignment x" and in it they tag the instructors and provide a link to the last commit 
- the grader provides detailed feedback right in that issue (and we record a mark and possibly some comments for for our own internal use in a different private place)

We've only been enforcing github and submiting hw through github for the last two course offerings I think so it's still a WIP. I think @jennybc has plans to change that a bit this coming fall

**Comment by jennybc** [comment]
Hi @vnijs. I'm excited to converse with other people using GitHub and the like for teaching!

I do plan to detail the STAT 545 approach in Happy Git, but @daattali's sketch gives you a good sense of what we do. I want to do that during July.

But, yeah, we do not have "HW as pull request". As Dean says, all student work is in student-specific repos that are not forks. We provide feedback in issues. We also elicit peer reviews via issues, which has worked very well.

However I definitely see the utility of the PR workflow re: the ease of commenting on specific lines. We don't have that.

**Comment by vnijs** [comment]
Very interesting @daattali @jennybc. Are your comments to the students public to other students? I'm very interested to learn more about how you setup peer review via issues. I expect we could do something similar with the PRs. 

[This page](http://www.princeton.edu/~mjs3/soc504_s2015/submitting_homework.shtml) describes the general work flow we are going for except that forking and PRs will be managed centrally by faculty/TA through the gitlab API. I'll let you know how it goes.

**Comment by jennybc** [comment]
Yes all the comments (but not marks) and, in fact, all student work is visible to other students. In general, this has worked well. I think they learn a lot about giving feedback that is specific and constructive and that doesn't need to be private. And I've been fortunate that my TAs also understand and implement this.

I had a plagiarism problem this year that will change my workflow. I will now make one student repo *per homework*. They will be invisible to other students until the due date. Once homework submission ends, I will flip a switch and make the repos visible among the students, as usual.

**Comment by vnijs** [comment]
I like the idea of open (and peer) feedback. I assume you use the github API to 'flip-the-switch'? Is there a code example you could share?

**Comment by jennybc** [comment]
I am now admitting that my "GitHub in the classroom" content has grown stale and, given that I'm no longer a prof, will only grow more stale. Luckily, others have picked up this banner. For example:

https://arxiv.org/abs/1811.02021

Using GitHub Classroom To Teach Statistics
Jacob Fiksel, Johanna S. Hardin, Leah R. Jager, Margaret A. Taub
(Submitted on 5 Nov 2018)

Git and GitHub are common tools for keeping track of multiple versions of data analytic content, which allow for more than one person to simultaneously work on a project. GitHub Classroom aims to provide a way for students to work on and submit their assignments via Git and GitHub, giving teachers an opportunity to teach these version control tools as part of their course. In the Fall 2017 semester, we implemented GitHub Classroom in two educational settings--an introductory computational statistics lab and a more advanced computational statistics course. We found many educational benefits of implementing GitHub Classroom, such as easily providing coding feedback during assignments and making students more confident in their ability to collaborate and use version control tools for future data science work. To encourage and ease the transition into using GitHub Classroom, we provide free and publicly available resources--both for students to begin using Git/GitHub and for teachers to use GitHub Classroom for their own courses.
