### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by jennybc** [jennybc/happy-git-with-r#3]
@daattali I want to deploy this site, skeletal though it may be, before tomorrow's dry run. That's my late afternoon / late night work plan for today. It's all meetings for me until then 😟. If you have a chance to offer an informed opinion on where/how to deploy this, I'd love to hear it. You can read about bookdown deployment options in this chapter:

https://bookdown.org/yihui/bookdown/publishing.html

**Comment by jennybc** [comment]
I obviously plan to start porting more content over ASAP as well, but that largely exists already! Getting deployment sorted out actually concerns me more.

**Comment by daattali** [comment]
Sorry Jenny I was in appointments all day and just got home, you caught me on a bad day! I'll take a look soon

**Comment by jennybc** [comment]
That's where I am too.

**Comment by jennybc** [comment]
Maybe I'll focus on bringing some content over and see if you have any words of deployment wisdom for me in the next little while.

**Comment by daattali** [comment]
Deployment looks very easy!  There's two options:

- option #1 is to publish using RStudio Connect and it will be hosted on bookdown.org
https://bookdown.org/daattali/happy-git-with-r/
This is very very simple. Every time we make a change, we need to render the book (using bookdown::render_book()) and then call `bookdown::publish_book()`

- option #2 is to host on GitHub and use GitHub Pages. This is not too bad supposedly but will be a bit more work initially. If we do this, then we can set up travis so that every time we push a commit to the repo, it will re-render the book automatically.  Option 1 is easier :)

**Comment by jennybc** [comment]
Re: option 1. I thought about that. But this is going to through a very awkward teenager phase and I don't want it up there during that time. But I don't want to wait until it's very developed to attempt the "real" deployment. That never ends well. I want to know I can fling it up there but have it be very obscure until we think it's ready for human eyeballs. From my quick read, wasn't clear if/how that would work. Can you determine that or conduct a small experiment?

Agree option 1 is easier. Though I'd love to sort out option 2. This is all a pilot study for larger renovations of STAT 545 stuff generally ....

**Comment by daattali** [comment]
They do support the option of having it only visible to a whitelist of people, so that's not a problem. See image below.  If option 1 is good enough for useR, I'd prefer to go with that. Because of time constraints I'd rather go the easier route for now and experiment with the github option next month?

![image](https://cloud.githubusercontent.com/assets/952340/16071563/ea6a4aba-3290-11e6-94f3-42a5ffea6b63.png)

**Comment by jennybc** [comment]
BTW I did exactly what you say re: RStudio Connect last week when I started this.

But when I logged back in, I could find no evidence of it. If I edit your URL and insert my username, it 404s. So is that some sort of temporary preview thing???? Or have I done something really odd?

We would need to understand this very well. I'm not sure it's really built for serving something like what we need. I want stability, I want to rip this content out of STAT 545 and have it live in exactly one place. I want to tweet this link. 

I suspect we should bite the bullet and do the travis + github pages thing.

**Comment by daattali** [comment]
I don't think it should get deleted, it should definitely still be there... if you go to https://bookdown.org/connect/#/documents do you not see anything?

**Comment by jennybc** [comment]
No, no documents found. But **I think I deleted it.** I think this is really about the URL at this point. Well, that, and you sweating through the travis stuff 😅.

**Comment by daattali** [comment]
OK if you really want to do a github deploy, we can do that. I got it working with my version: http://daattali.github.io/happy-git-with-r/

It's actually not too bad.  If you want to make the CURRENT repo a github page, it'll be at jennybc.github.io/happy-git-with-r so maybe you'll want to create a new git user for this, or somehow make the URL a bit better?  

The steps are:
- add a file `.nojekyll`
- create a `gh-pages` branch
- create a [build script](https://github.com/daattali/happy-git-with-r/blob/master/_build.sh) that will render the book 
- create a [deploy script](https://github.com/daattali/happy-git-with-r/blob/master/_deploy.sh)
- create a GitHub PAT that has "repo" permission and set the global variable `GH_TOKEN` on your travis machine
- [call the build & deploy scripts with travis](https://github.com/daattali/happy-git-with-r/blob/master/.travis.yml#L16-L22)
- every time you push a commit with any change in the book content, the book will get regenerated and the website will have the updated version within minutes

I'll be in Berkeley starting the 19th - when are you arriving to the area?  I'm pretty sure your travis and github knowledge is better than mine so I'd feel more comfortable if we do this together for the real deal

**Comment by jennybc** [comment]
Maybe it's time to get another domain name? Thanks for piloting all of that. Agree I should be able to close the deal.

**Comment by daattali** [comment]
I think spending the ~15$ yearly for a domain would be totally worth it if
you plan on using this git book more long term.

**Comment by jennybc** [comment]
Suggestions for domain name are welcome.

**Comment by daattali** [comment]
Is this book planned to remain focused on git and r?

**Comment by jennybc** [comment]
yes I think so

**Comment by jennybc** [comment]
ACK! This, this is exactly what I don't want. Somehow your version of this non-existent book is on the front page of bookdown.org. CAN YOU BRING THAT DOWN ASAP?

<img width="915" alt="screen shot 2016-06-16 at 1 16 08 pm" src="https://cloud.githubusercontent.com/assets/599454/16131727/8c3d996c-33c4-11e6-84e2-0a9a093a603e.png">

I want to know how to develop, deploy, develop, deploy .... and *eventually* publicize.

BTW how did you even do that? For me `bookdown::publish_book()` only puts it at:

https://beta.rstudioconnect.com/jennybc/happy-git-with-r/

**Comment by daattali** [comment]
Huh, I guess they automatically show the most recent. OK it's deleted now, but there's still a link on that page that now goes to a 404 and will probably be removed soon.  Not sure why my `publish_book` went to the real website and not to a beta Connect :S  Do you want me to take down http://daattali.github.io/happy-git-with-r/ too? That link is not posted anywhere except here

**Comment by jennybc** [comment]
This is exactly why I deleted my Connect project last week when I paused working on this. (And then promptly forgot about that, then wondered where it went ...).

I don't really care about the other link but maybe yes bring it down next chance you get.

I opened an issue on bookdown asking about this.

**Comment by jennybc** [comment]
I am now the proud owner of

happygitwithr.com

So I guess this is the plan:

travis to build

deploy to GitHub pages

custom domain

**Comment by daattali** [comment]
and you're also the proud owner of a brand new selfie and github bio!

Good domain.  This of course doesn't change anything as far as build/deployment goes. The domain should just be a one-time setup thing. I haven't tried setting up a CNAME with a github repo that isn't your `username.github.io`, but I imagine it works easy enough

**Comment by jennybc** [comment]
The selfie is because the Faces API thought I was 50 based on a previous one! Good grief. I had to fix that, but honesty compels me to use a recent photo. Taken today in fact.

**Comment by jennybc** [comment]
Got this working. Quick notes.

Good example: https://github.com/coatless/statprogramming.

That basically follows the directions here: https://bookdown.org/yihui/bookdown/github.html.

Moving parts = build script, deploy script, create new PAT, encrypt and put into .travis.yml, turn travis for repo.

Something that was very important on Travis but is mentioned nowhere: have a DESCRIPTION file. Put `bookdown` in Imports and Remotes.

Key bits re: custom domain:

  * CNAME file holds just this:  happygitwithr.com
  * sceengrab of DNS set up on hover

<img width="840" alt="screen shot 2016-06-21 at 9 59 39 am" src="https://cloud.githubusercontent.com/assets/599454/16238810/cda2fee4-3796-11e6-9fb5-7f9ebd475987.png">
