### ISSUE TITLE
19.9 - rmarkdown installation error

### ISSUE THREAD

**Issue by samhinshaw** [jennybc/happy-git-with-r#35]
Installing "rmarkdown" through rstudio GUI errors due to dependency installation "base64enc".  Installing package via `install.packages("rmarkdown")` in console successfully completes installation

**Comment by jennybc** [comment]
When you say this:

> Installing "rmarkdown" through rstudio GUI

do you literally mean the Packages tab in what is usually the lower right pane?

**Comment by samhinshaw** [comment]
I specifically noticed the error when students accepted this prompt (image pulled from google):
![rmarkdown](https://cloud.githubusercontent.com/assets/14186005/18521446/ff5be880-7a60-11e6-9582-9e2ac0b29e93.png)

I believe the results of accepting this prompt are *different* from installing a package via the "Packages" tab, as accepting the prompt results in a popup, rather than running the command in the console. The process is actually [on youtube](https://www.youtube.com/watch?v=QaKCirYknS8), except the error closes out the "installing packages" popup window so the error cannot be read.

**Comment by jennybc** [comment]
Thanks. Another question:

> errors due to dependency installation "base64enc". 

What does this mean? rmarkdown installation fails because `base64enc` is not installed or is not up-to-date or cannot be installed or ?? Or is that the error that you are unable to read?

**Comment by samhinshaw** [comment]
So I believe [this may be the exact error](https://support.bioconductor.org/p/86423/), where base64enc is installed as a dependency. (This is just from what I was able to read as the error message flew by on the screen.) But it seems that for some reason the dependency does not install in the pop-up window--but it installs when you type the `install.packages()` command into the console.

**Comment by jennybc** [comment]
Thanks @samhinshaw! Do you remember how many times you and @oganm saw this on Tuesday? Was it always on a specific OS?

**Comment by samhinshaw** [comment]
I saw the error twice on windows machines, and I *think* I saw it once on a mac, but I may be misremembering that.

**Comment by jennybc** [comment]
Thanks for all the answers. @kevin_ushey thinks this is either due to a recent, temporary glitch with Windows binary packages on CRAN or something that is hopefully fixed in RStudio (by tomorrow). I will leave this open in case we have more trouble. But if time passes and all is well, we will just close and let it by a mystery.
