### ISSUE TITLE
Notes for GitHub use in classroom

### ISSUE THREAD

**Issue by jennybc** [jennybc/happy-git-with-r#39]
2016 outline (most of these requests have additional info in the body btw):
- get GitHub username via Shiny form app
- ping them to make sure exist `GET /users/:username`
  - all did (!!) but some typos, of course, which were all valid usernames, which meant I invited randos to join the org at first (all straightened out now)
- create 2016_students name and store id `POST /orgs/STAT545-UBC/teams`
- invite students to join the team (and therefore org) `PUT /teams/:id/memberships/:username`
- create student-specific repos `POST /orgs/STAT545-UBC/repos`
- add student as collaborator `PUT /repos/STAT545-UBC/:repo/collaborators/:username`
- grant 2016_students team read access to all student repos `PUT /teams/:id/repos/STAT545-UBC/:repo`
- unwatch all the repos personally `DELETE /repos/:owner/:repo/subscription`
- iterate endlessly as students gradually register, fill out the form, etc.

First year I have not created singleton teams and granted repo access solely through singleton team membership. In 2014 that was necessary due to restrictions in team/org permissions. By 2015 that had changed, but the change was very new and I didn't change my behaviour. 2016 is the first year I've taken advantage of fact you can add individuals as collabs to private Org-owned repos.

And here's a peculiar consequence.

Students can start pushing their repos right away. Specifically, can do so w/o accepting the invitation to join the Org. You discover this when you try to assign them peer review. `POST /repos/:owner/:repo/issues` gives 422 whenever the putative reviewer (who will be specified as assignee in the body of the request) is not a member of the 2016_students team, which is what confers the necessary read access.

**Comment by hathawayj** [comment]
If at all possible, it would be great to have the full R script that is described above.  Hoping you can easily remove any identifiable information...

**Comment by jennybc** [comment]
I feel like you're looking over my shoulder! I am literally writing a section of an article on this right now 😁. That will necessarily be fairly high level, so doesn't solve your problem. I'll reply to your email. I may have to provide you my actual script via email -- despite the obvious and painful irony -- since I can't immediately post my actual scripts on GitHub. Creating versions that I can post remains very much a goal of mine.

**Comment by hathawayj** [comment]
Thanks.  I look forward to the email.

**Comment by hathawayj** [comment]
Do you have a link to the article that I could reference?

**Comment by jennybc** [comment]
@hathawayj The article will have a public link soon at PeerJ. I can provide you a copy in the meantime, if it would be useful? Not sure of context.

**Comment by hathawayj** [comment]
Thanks.  We are developing an undergraduate course in a similar flavor to your course (http://stat545.com/index.html).   It is still draft but can be found here (https://byuistats.github.io/M335/index.html).  We will have students use Github as you have done and I figured staring at your actual code would make it easier for me than the pseudo code above.

I am not at the stage of trying to get the Github classroom to work as I expect.  I would love a copy.  I will email you to get the copy.

**Comment by hardin47** [comment]
Is it too much to ask for you to send it to me, too?  Thank you!!

**Comment by jennybc** [comment]
@hardin47 Sure. I'm about to forward the email I sent to @hathawayj to you.

**Comment by jennybc** [comment]
I am now admitting that my "GitHub in the classroom" content has grown stale and, given that I'm no longer a prof, will only grow more stale. Luckily, others have picked up this banner. For example:

https://arxiv.org/abs/1811.02021

Using GitHub Classroom To Teach Statistics
Jacob Fiksel, Johanna S. Hardin, Leah R. Jager, Margaret A. Taub
(Submitted on 5 Nov 2018)

Git and GitHub are common tools for keeping track of multiple versions of data analytic content, which allow for more than one person to simultaneously work on a project. GitHub Classroom aims to provide a way for students to work on and submit their assignments via Git and GitHub, giving teachers an opportunity to teach these version control tools as part of their course. In the Fall 2017 semester, we implemented GitHub Classroom in two educational settings--an introductory computational statistics lab and a more advanced computational statistics course. We found many educational benefits of implementing GitHub Classroom, such as easily providing coding feedback during assignments and making students more confident in their ability to collaborate and use version control tools for future data science work. To encourage and ease the transition into using GitHub Classroom, we provide free and publicly available resources--both for students to begin using Git/GitHub and for teachers to use GitHub Classroom for their own courses.
