### ISSUE TITLE
Syncing a fork in the browser with GitHub is not a sustainable workflow

### ISSUE THREAD

**Issue by dmurdoch** [jennybc/happy-git-with-r#40]
You give two sets of instructions for syncing a fork.  To work purely on Github, you link to the page

http://www.hpique.com/2013/09/updating-a-fork-directly-from-github/

That's a bit out of date (some button labels have changed), but more importantly, it doesn't work.  I had the same problem as several of the commenters:  it creates a pull request to do the update; after I accept that pull request on my fork, I'm out of sync with the upstream, and can't do it again.

I haven't tried the command line instructions yet, but they make more sense.  I just wish there were a way to do them online.

**Comment by jennybc** [comment]
Thanks @dmurdoch. I feel like I succeeded with that web flow once? But I admit I have not used it myself in many moons.

I will see if I can find a GitHub-based method that works today. Or work one out myself. Agree it would be nice.

**Comment by dmurdoch** [comment]
It works once, just not a second time.  Part of the comments to that post ask people to bring it up with Github support; I wrote to them, and they replied "This request is definitely something that's on our radar, and we absolutely hear our users asking for us to solve this issue."  So it may not be worth spending time on a Github-only solution.  There's probably a non-command line solution using the front ends you recommend, though.

**Comment by jennybc** [comment]
@dmurdoch I just revisited this and tried every possible thing I could think of in the browser. I still conclude, as you have, it is currently an unsustainable workflow 😔.

It's easy to create the reverse pull request. In your own fork, click "New pull request" then click on "switching the base" to invert the role of your fork and the original.

<img width="1002" alt="screen shot 2017-05-30 at 1 52 53 pm" src="https://cloud.githubusercontent.com/assets/599454/26690902/f8c1c212-46af-11e7-9ede-0cd622bda274.png">

But every possible method of merging that PR into your own fork leaves you in a state where your history is different from the base. I tried with "create a merge commit", "squash and merge", "rebase and merge".

**Comment by johnmackintosh** [comment]
Small sample size but the link
 http://www.hpique.com/2013/09/updating-a-fork-directly-from-github/
doesn't appear to be accessible any more, at least not the few times I've tried over last couple of days

**Comment by jennybc** [comment]
@johnmackintosh OK I'll look into that. But given that this strategy doesn't really work more than once, it's no great loss. I need to revise the section.

**Comment by johnmackintosh** [comment]
No probs, just to let you know in the unlikely event you missed it. 
Think I'm going to burn down my repo and start again anyway.
Thanks again for this resource, it should really be the first place signposted to all R users who need to learn Git.

**Comment by revodavid** [comment]
All seems to be working now, with this process: https://twitter.com/revodavid/status/1187435324353302534

**Comment by jennybc** [comment]
@revodavid do you want to open another issue and/or PR to restore our coverage of a browser-based workflow for this?

**Comment by revodavid** [comment]
Happy to add an issue, but I won't be able to submit a PR for quite a while.
