### ISSUE TITLE
rstudio::conf tutorial attendees: What's your OS?

### ISSUE THREAD

**Issue by jennybc** [jennybc/happy-git-with-r#44]
Issue opened for use during Happy Git and Gihub for the useR tutorial at [rstudio::conf 2017](https://www.rstudio.com/conference/).

Use an emoji reaction to indicate which operating system you use.

**Comment by jennybc** [comment]
macOS Sierra – version 10.12

**Comment by jennybc** [comment]
OS X El Capitan – version 10.11

**Comment by jennybc** [comment]
OS X Yosemite – version 10.10

**Comment by jennybc** [comment]
OS X Mavericks – version 10.9 or
OS X Mountain Lion – version 10.8

**Comment by jennybc** [comment]
Windows 7

**Comment by jennybc** [comment]
Windows 8

**Comment by jennybc** [comment]
Windows 10

**Comment by jennybc** [comment]
Ubuntu or Debian

**Comment by jennybc** [comment]
RedHat, CentOS, fedora, or any other flavour of Linux

**Comment by OmaymaS** [comment]
Windows 10

**Comment by vhmedina** [comment]
OS X El Capitan

**Comment by Curt-Younkin** [comment]
OS X El Capitan 10.11.6
👍

**Comment by KirbyArinder** [comment]
Mac 10.11. I have no idea how to put an emoji here.

**Comment by Curt-Younkin** [comment]
Little emoji button in the upper right of previous comments

**Comment by daluque** [comment]
Windows 7
