### ISSUE TITLE
Pick a basic markdown tutorial

### ISSUE THREAD

**Issue by jennybc** [jennybc/happy-git-with-r#5]
Here I refer to "homework 1", mostly for basic knowledge/practice with markdown. It should be easy to swap that out with something external.

http://stat545.com/block007_first-use-rmarkdown.html#step-0-software-installation-and-configuration

**Comment by daattali** [comment]
May I suggest http://www.markdowntutorial.com/

**Comment by jennybc** [comment]
It no longer feels necessary for Happy Git to have an opinion on where to learn markdown syntax.
