### ISSUE TITLE
troubleshooting confusion over SSH vs HTTPS

### ISSUE THREAD

**Issue by johngoldin** [jennybc/happy-git-with-r#53]
I just spent two hours trying to figure out why I could push from my laptop and not from my desktop. Turns out I was a bit glib cloning the project on the desktop and ended up with the HTTPS repository url on the desktop. I was able to pull and pass the tests for whether github would take my SSL. So took me quite a while to solve my problem. My suggestion is to add a bit of warning to section 13.7:

If you think SSH is working and you are still challenged for your credentials, check your project options and make sure that the the project origin starts with git@github.com (not with HTTPS:).

[It turns out I still don't know how to change the project origin once I screwed it up. I had to burn it down on my desktop RStudio and clone it again. If I had followed the instructions more carefully, I wouldn't have had this problems, but who follow directions?]

**Comment by jennybc** [comment]
Thanks for this! I have definitely seen this and talked about it in live workshops, so it's a good idea to bring in back into the prose as well.
