### ISSUE TITLE
satRday Cape Town workshop attendees: What's your OS?

### ISSUE THREAD

**Issue by jennybc** [jennybc/happy-git-with-r#55]
Issue opened for use during Happy Git and GitHub for the useR workshop at [satRday Cape Town](http://capetown2017.satrdays.org).

Use an emoji reaction to indicate which operating system you use.

**Comment by jennybc** [comment]
macOS Sierra – version 10.12

**Comment by jennybc** [comment]
OS X El Capitan – version 10.11

**Comment by jennybc** [comment]
OS X Yosemite – version 10.10

**Comment by jennybc** [comment]
OS X Mavericks – version 10.9 or
OS X Mountain Lion – version 10.8 or
any Mac OS not listed here

**Comment by jennybc** [comment]
Windows 10

**Comment by jennybc** [comment]
Windows 8

**Comment by jennybc** [comment]
Windows 7 or
any Windows not listed here

**Comment by jennybc** [comment]
Ubuntu or Debian

**Comment by jennybc** [comment]
RedHat, CentOS, fedora, or
any other flavour of Linux

**Comment by AlwynDp2** [comment]
AWE bra! windows 7

**Comment by HanjoStudy** [comment]
[There is but one](https://assets.ubuntu.com/v1/590018e7-picto-ubuntukylin.svg)
