### ISSUE TITLE
happy-docker-with-r

### ISSUE THREAD

**Issue by t-kalinowski** [jennybc/happy-git-with-r#57]
Hi,

I really appreciate "Happy git with R."

How amazing would it be if there was a 2nd installment in the series called "Happy Docker with R"? 

I, for one, would love that.

Please consider it.

Kind regards,
Tomasz

**Comment by jennybc** [comment]
If/when I take the plunge, I'll think about it 😅

**Comment by t-kalinowski** [comment]
Thank you!
