### ISSUE TITLE
SSH keys

### ISSUE THREAD

**Issue by jennybc** [jennybc/happy-git-with-r#6]
@Anmol6 Please don't do this yet.

I have a lot of content to migrate over after today's practice run. I will stub something out for you. But you can expect this request from me very soon: bring the SSH key setup instructions over from MDS set up repo.

**Comment by jennybc** [comment]
@Anmol6

Hello! I think I glimpsed you on Wednesday but caught up in the troubleshooting, but then you had to go to class. Sorry we didn't meet properly.

I have a place for you to put the SSH setup now, if you're still willing. Have you made a pull request before? Would you like to do that here?

Can you read some of the other material, especially the instructions re: HTTPS credential caching, to get a feel for this? So you can draft something that feels similar.

Also read the SSH section here:

<http://r-pkgs.had.co.nz/git.html#git-init>

It looks like this can be done from RStudio. Maybe that is our preferred option? You'll have to try it. I've always done this from the shell. Perhaps it's best to have both in our site, just to be safe.

Thanks and let me know if you have questions or won't be able to do this.

**Comment by jennybc** [comment]
@Anmol6

Did you see this? I am currently linking out to good instructions, so that is my current plan.

**Comment by Anmol6** [comment]
@jennybc yup, sorry for the late response. 

I have the shell instructions for SSH/https authentication. Do you want me to add those via a pull request?

**Comment by jennybc** [comment]
Yes that would be great. Thanks.

**Comment by Anmol6** [comment]
@jennybc , I have added the instructions for ssh keys via shell. Could you take a look and let me know if I should change anything?
One problem I keep having with markdown is formatting the numbers in lists properly. I haven't been able to fix this.

**Comment by jennybc** [comment]
This has been done now.
