### ISSUE TITLE
RStudio not recognising Git in windows 7 64bit system

### ISSUE THREAD

**Issue by pm321** [jennybc/happy-git-with-r#61]
Please find attached detailed account of attempts to link up RStudio and Git.

I have followed the instructions in your excellent, clearly written guide to using git and R.
However, I am struggling to get RStudio to recognise Git. I am at a loss to know what to do as I had a previous version of Git that was working on my computer and for some inexplicable reason Git and RStudio no longer work together. I am afraid I cannot recall what I may have done to cause the disassociation between RStudio and Git.

I have completely uninstalled R, RStudio and Git and re-installed all applications but still have the issue that RStudio does not recognise Git.

In summary:
Git is installed on my computer (OS - Windows 7 64 bit) 
RStudio has identified the git.exe file and path in Tools | Global options | Git/SVN
But when I try to set up a New Project or try to checkout a project from a version control repository – I get  the “Git was not detected on the system path” error message.
Echo $PATH in the Git Bash shell did not include  “Git”
Editing the PATH variables in windows has not resolved the issue.

Screen shots of the attempts to resolve this are included in the attached file.

Happy to help in any other way to try to resolve this.

 
[RStudio not recognising Git.docx](https://github.com/jennybc/happy-git-with-r/files/1022535/RStudio.not.recognising.Git.docx)

**Comment by jennybc** [comment]
I will see @kevinushey this week and see if the above rings a bell.

**Comment by jennybc** [comment]
Do you NOT have admin permission on this machine?

**Comment by pm321** [comment]
Hi Jenny,

Thanks for your response.

I do have admin permission on my personal computer (pc):

My day to day work is carried out under a user account (PDM) which is set to ‘Administrator’ account type.

The MS ‘default’ Administrator account is a separate account which I tend not to use – this one is password protected (PDMAdministrator).

So the pc has two Administrator user accounts.




Regards

Peter

**Comment by kevinushey** [comment]
I can't think of what might be wrong here other than a potentially borked Git installation. Does uninstalling and reinstalling Git make a difference?

Current best guess -- the warning messages seen in the terminal (in the attached Word document) seem to suggest that either something went wrong during installation, or perhaps that Git + its ecosystem was not installed with the permissions it requires for normal functionality.

**Comment by jennybc** [comment]
I'm grooming issues and Happy Git. While I lament the trouble here, I don't currently see what, if anything, we can take away to improve the instructions.

**Comment by pm321** [comment]
Hi Jenny,

Many thanks for looking at this.

I resolved the issue by a complete re-install of  Windows 7. A bit of a pain but Git is back – hurrah.


Regards

Peter

**Comment by jennybc** [comment]
OK glad you are sorted out.
