### ISSUE TITLE
CSAMA 2017 participants: What's your OS?

### ISSUE THREAD

**Issue by jennybc** [jennybc/happy-git-with-r#62]
Issue opened for use during Happy Git and GitHub for [CSAMA 2017](http://www.huber.embl.de/csama2017/).

Use an emoji reaction on the relevant comment below to indicate which operating system you use.

**Comment by jennybc** [comment]
macOS Sierra – version 10.12

**Comment by jennybc** [comment]
OS X Yosemite – version 10.10

**Comment by jennybc** [comment]
OS X Mavericks – version 10.9 or
OS X Mountain Lion – version 10.8 or
any Mac OS not listed here

**Comment by jennybc** [comment]
Windows 10

**Comment by jennybc** [comment]
Windows 8

**Comment by MeganDruce** [comment]
:)

**Comment by jennybc** [comment]
Windows 7 or
any Windows not listed here

**Comment by SabrinaKruse** [comment]
Windows 10

**Comment by jennybc** [comment]
Ubuntu or Debian

**Comment by jennybc** [comment]
RedHat, CentOS, fedora, or
any other flavour of Linux

**Comment by cimbusch** [comment]
macOS 10.12.5

**Comment by naso4317** [comment]
Win 10

**Comment by cimbusch** [comment]
SPAM SPAM SPAM

**Comment by MeganDruce** [comment]
macOS 10.11.6

**Comment by santiago1234** [comment]
macOS 10.12.4

**Comment by dl016d** [comment]
macOS 10.12.5

**Comment by chenhong-dkfz** [comment]
maaaaaaaacOS 10.12.5

**Comment by mattiafalcone** [comment]
👍

**Comment by ToreBle** [comment]
macOS 10.12.5

**Comment by dordonezb** [comment]
OS X 10.11.5

**Comment by FiRi84** [comment]
**macOS** Sierra

**Comment by mreitberg** [comment]
mac OS Sierra 10.12.5 
tremendous

**Comment by mattiafalcone** [comment]
mac OS 10.11.6
HUGE

**Comment by priyac3005** [comment]
Windows 10

**Comment by borshago** [comment]
Ubuntu 16.04 + Windows 10 dual boot

**Comment by RebeccaHalbach** [comment]
Ubuntu16.04

**Comment by perlfloccri** [comment]
Windows 10

**Comment by Tatatin** [comment]
macOS Sierra 10.12.4

**Comment by CLoretelli** [comment]
Windows 10

**Comment by KorbinianBsl** [comment]
Archlinux 4.11.3

**Comment by lwaldron** [comment]
macOS Sierra 10.12.5

**Comment by lgatto** [comment]
```
lg390@elyacin [02:54:16] [~] [master *]
-> % uname --all
Linux elyacin 3.13.0-107-generic #154-Ubuntu SMP Tue Dec 20 09:57:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jotsetung** [comment]
macOS Sierra 10.12.6 Beta - bad idea actually
