### ISSUE TITLE
Git Versions and Credentials

### ISSUE THREAD

**Issue by andyanderson** [jennybc/happy-git-with-r#66]
On this page:

http://happygitwithr.com/credential-caching.html#verify-that-your-git-is-new-enough-to-have-a-credential-helper

You write “verify your version is 1.7.10 or newer,” implying this is required for credentialing.  

Near as I can tell, credentialing has been present in Git for a long time, e.g. it is present in our version 1.7.1 on Linux. The only new thing with version 1.7.10 seems to be that it adds credential-osxkeychain:

https://help.github.com/articles/caching-your-github-password-in-git/

where it says: “You need Git 1.7.10 or newer to use the osxkeychain credential helper.”

It’s a good idea to keep git up-to-date (when you can), but this detail sent me on a bit of wild goose chase to understand why some things worked and some things didn’t.

Thanks for a great document!

**Comment by jennybc** [comment]
Would you like to make a PR with better wording?

I still can't tell from the above whether current wording:

a) made you re-install / update unnecessarily (it's too strong)
b) did not warn you sufficiently about the need to update to get the keychain credential helper (it's too weak)

**Comment by jennybc** [comment]
I am making updates to these sections and I believe we are current.
