### ISSUE TITLE
bash: remote: command not found

### ISSUE THREAD

**Issue by Igneous01** [jennybc/happy-git-with-r#70]
This issue looks to be related to #67 

I just installed git using the exact same settings as OP and I get the same issue:

![image](https://user-images.githubusercontent.com/5571589/33692921-c76edf4a-dabd-11e7-9c51-5a513265810a.png)

I tried OPs suggestion and reinstalled (checking use git from windows command prompt option) but it still does not work.

I'm not able to get Git CMD Working either (Although maybe I dont understand the difference between GitCMD and Git Bash):

![image](https://user-images.githubusercontent.com/5571589/33692903-b951ef42-dabd-11e7-9266-1b2d778cf1fd.png)

**Comment by jennybc** [comment]
You need to type `git remote -v`. The command is `git remote` not `remote`.

**Comment by chaoweiliang1001** [comment]
yeah
