### ISSUE TITLE
Issue and workarounds for git2r + Windows + SSH

### ISSUE THREAD

**Issue by ijlyttle** [jennybc/happy-git-with-r#74]
Hi @jennybc,

I figure you are super-busy right now, so to be clear I have no need for an immediate solution here. 

On my Windows machine, I have gone through the steps [you outline](http://happygitwithr.com/ssh-keys.html#create-an-ssh-key-pair) for SSH on Windows: 
Git Bash ->`eval $(ssh-agent -s)` -> `ssh-add ~/.ssh/id_rsa`. 

I can `ssh -T git@github.com` and push-pull with RStudio IDE no problem.

When I try to use `usethis::use_github()`, I run into a problem. I have traced it to `git2r::push()` and can reproduce it:

```R
git2r::push(git2r::repository(usethis::proj_get()), "origin", "refs/heads/master")
```

```
Error in .local(object, ...) : 
  Error in 'git2r_push': error authenticating: failed connecting agent
```

Also, the problem might be that my corporate load of Windows 7 might be doing something funny.

I know I should work on this to file a proper issue somewhere (once I have a better idea of what the problem *actually* is), but I wanted to give you a heads-up just in case any of your upcoming students might run into the same thing. 

A colleague and I came up with a workaround [here](https://ijlyttle.github.io/ghentr/articles/workarounds.html#windows-7-and-ssh). It's a bit of a bear, but we do get it to work.

**Comment by jennybc** [comment]
Yeah I have done battle with git2r and passphrase-protected SSH keys before.

I cannot summon all the details at the moment, though. Will investigate.

**Comment by jennybc** [comment]
Very helpful document! So at least one of the problems you've identified has been seen and solved here and should probably get transmitted to git2r as well:

https://github.com/r-lib/usethis/issues/183

**Comment by jennybc** [comment]
More confirmation of how to handle the location of `.ssh/` on Windows:

https://github.com/rstudio/rstudio/blob/1a6200903f6d245aaa921e7dcb70f314ae3dd41e/src/cpp/session/modules/SessionVCS.cpp#L182-L196

**Comment by ijlyttle** [comment]
Thanks! I'm glad (?) but not surprised that you've already been over this ground with Windows. 

I'll file an issue with git2r; you've given me enough to get a good head-start!

I don't know if this needs to remain an open issue here. I'll close, but post updates; it will not hurt my feelings if you re-open.

**Comment by jennybc** [comment]
I want to document how to handle this situation in the here and now, so re-opening.

**Comment by jennybc** [comment]
I can confirm this is not specific to Windows 7. I can get same error on Windows 10.

**Comment by jennybc** [comment]
I had success like so:

``` r
cred <- cred_ssh_key(publickey = "~/../.ssh/id_rsa.pub", privatekey = "~/../.ssh/id_rsa")
use_github(credentials = cred)
```

Scenario: passphrase-protected SSH, where the ssh-agent is successfully setup to provide the passphrase. This is basically an alternative to the link or alias for  `.ssh/` proposed in @ijlyttle's workaround doc.

**Comment by ijlyttle** [comment]
Cool! 

FWIW I am not convinced, in my case, that git2r knows about my ssh-agent. It's almost as if they are existing in different universes. For me, git2r relies on getPass for the popup to supply the passphrase.
