### ISSUE TITLE
RStudio not finding Git on Mac OS

### ISSUE THREAD

**Issue by jennybc** [jennybc/happy-git-with-r#8]
In today's practice run at UBC, we had two troublesome computers. Both Macs (!!!). OS versions were 10.10.5 Yosemite (@MarinStatsLectures) and 10.9.5 Mavericks (Natalia). FWIW current is 10.11 El Capitan.

Problem: RStudio never could use Git. The Git pane did not appear.

What I know (I hope @ttimbers will confirm):
- both installed from here: https://git-scm.com/downloads
  - for the 10.9.5 machine, we worked with git 2.8.1 intel universal mavericks
  - should my [Mac git install instructions](http://stat545.com/git01_git-install.html#git-installation-mac) have an option 0, which is to do nothing and use git that ships with mac os?
  - why do I not mention Xcode command line tools here? does it not install git?
  - should I sell homebrew harder?
- `which git` revealed a git executable for both
- git could be used from the command line for both
- `echo $PATH` revealed that the location of the git executable was indeed on the path
- we restarted RStudio, Terminal, logged out, logged back in ... nothing helped
- we could point RStudio at the git executable, i.e. the _Tools > Project or Global Options > Git/SVN_ dialogue box appeared to refer to the desired executable
- RStudio was very current (both running Preview?)

But we don't get the Git tab in upper right pane. Can't check "create git repo" for new projects. Etc etc.

**Comment by jennybc** [comment]
Troubleshooting tips from @kevinushey:

Check `Sys.which("git")` in addition to `which git`. Record what both return.

Inspect .gitconfig. Is there anything strange / surprising? E.g. in the project where git isn't working:

       git config --global --list
       git config --system --list
       git config --local --list

*Note that, if current project is NOT already a git repo, git config --local won't work for obvious reasons.*

Are there any git-related errors in the logs? (Help -> Diagnostics ->
Show Log Files; there should be a file 'rsession-<username>.log'; if
there was something emitted it should show up near the end of that
logfile)

Is it possible that the associated git config files have permissions
that disallow RStudio from reading them?

**Comment by jennybc** [comment]
More from @kevinushey:

Try moving the /usr/local/bin/git (a symlink) out of the way. Doe that help? Does OS X
fall back to a default version of git?

*not sure if that was tried or how it panned out* @ttimbers?

**Comment by kevinushey** [comment]
I should also double check -- has the git repository actually been initialized for that directory (has `git init` been called)? Does the `.git` directory exist in those projects?

I think that, if a `git` executable is detected / set, then the option to create new R projects with `git` initialized is provided, e.g.

<img width="551" alt="screen shot 2016-06-15 at 10 32 00 pm" src="https://cloud.githubusercontent.com/assets/1976582/16106406/03c85250-3349-11e6-9ae7-5022c64c7af9.png">

If the `Create a git repository` is not checked, then `git init` is not run as part of the project creation process, and then RStudio won't detect that the project is managed by git and hence won't show the Git pane.

FWIW, I did try using the version of git provided at https://git-scm.com/downloads and all seemed well.

**Comment by kevinushey** [comment]
It looks like RStudio does provide some UI for initializing a Git repository in a project -- within `Tools -> Project Options`, there should be an option for enabling Git, e.g.

<img width="566" alt="screen shot 2016-06-15 at 10 39 31 pm" src="https://cloud.githubusercontent.com/assets/1976582/16106552/41171208-334a-11e6-8228-e5eed498a402.png">

Was this dialog available in each case?

**Comment by jennybc** [comment]
We could navigate to this screen but the only entry in the Version control system dropdown was "(None)".

We simply had no access to Git functionality at all. For example, when creating a new repo *de novo*, there was no check box to make it a Git repo.

**Comment by kevinushey** [comment]
Looking a bit into the details of the source code, when deciding whether to show Git-related GUI, it checks:

1. Is VCS enabled? (this should be set in the Git/SVN tab of Global Options; given that the path to the Git executable is being set I believe this should be the case),

2. Can we successfully run `git --version`? That's used as the canary as to whether git can actually be used for that project.

We also have some special handling for Mavericks -- from comments in the source code, it sounds like Apple installed a 'dummy' version of `git` into `/usr/bin/git`, and one needs to install OS X developer tools to get the 'real' version of git.

I wonder if Mike and Natalia are able to run `/usr/bin/git --version` successfully? Maybe RStudio is inadvertently trying to use the version of `git` at `/usr/bin/git`, but that is failing for some reason (e.g. missing developer tools, borked system `git` installation for other reasons)?

**Comment by ttimbers** [comment]
@jennybc @kevinushey we did not get the chance to try to move the /usr/local/bin/git (a symlink) out of the way, but we did try adding the "true" git to the $PATH and then pointing RStudio there. That did not help.

**Comment by ttimbers** [comment]
@kevinushey yes, VCS was enabled on both of these machines via the  Git/SVN tab of Global Options, and we also set the path to the Git executable in that tab.

Although we did not test `git --version`, git did work from the command line and a git client (Git Kraken) on both machines. 

I will see Mike on Tuesday and see what happens when we try `/usr/bin/git --version`. But maybe what we need to recommend is that they install OS X developer tools to get the 'real' version of git.

**Comment by jennybc** [comment]
> VCS was enabled on both of these machines via the Git/SVN tab of Global Options, and we also set the path to the Git executable in that tab

Just to elaborate: we were able to set the path enough for RStudio to accept it and for it to persist when we left the dialogue box and came back. So RStudio acknowledged this git executable in some narrow sense. But the IDE never changes, i.e. no Git pane ever appears. And we get an actual error whenever we do anything that would cause RStudio to call Git. It's like we get past whatever logic governs this interface. But then this path is being overridden or ignored at the moment of truth.

> git did work from the command line and a git client (Git Kraken) on both machines.

Git Kraken calls libgit2, as GitUp does. So Git Kraken will work even in the complete absence of a functional local git installation. So the success from the command line is the real proof that we should be able to make RStudio do git things.

> recommend is that they install OS X developer tools

Yeah I am definitely re-writing the instructions today.

**Comment by nickreich** [comment]
I had this same problem even after installing XCode and the command line tools. It was fixed after I ran a simple command in the terminal like `git config --global --list` which then forced me to agree to the XCode license agreement. Then, restarted RStudio and it recognized that git was on my system.

**Comment by jennybc** [comment]
Thanks @nickreich! Helpful to have such reports.

**Comment by cmartin** [comment]
This also happened to me today. Newly updated RStudio and fresh install of git from git-scm.com after a macOS Sierra update.

I was also stumped by the RStudio git binary picker which looked correct at `/usr/bin/git`, but my actual git installation was at `/usr/local/bin/git` (as found with the `which git` command). Once I pointed RStudio to the correct git binary location, everything reappeared.

Hopefully this will be useful to others as well, this issue is in the top google results for "RStudio wont detect git"

**Comment by kevinushey** [comment]
@cmartin, if you just updated to macOS Sierra, then likely one of the side effects of that was that the command line tools were uninstalled. What happens if you try to run

    /usr/bin/git --version

from the terminal? If I'm correct, you should get a dialog asking you to reinstall command line tools -- please let us know if that was the case!

**Comment by jennybc** [comment]
Isn't there also a need and some way to trigger re-accepting the Xcode CLT EULA or whatever? After an OS upgrade?

**Comment by mcsiple** [comment]
I had this same problem and managed to fix with the following steps (using MacOS Sierra, 10.12.6):
- check global git repo ( git config --global --list )
- navigate to project repo using Terminal
- at this point I edited one of the files and pushed to the project repo, to test whether git was working w/o RStudio, but I don't think this was a necessary step
- run
`git init`
- close and reopen the project in RStudio 
- Git tab reappears

**Comment by joebowness** [comment]
My fix to this problem was to change the Git executable path in RStudio > Preferences > Git/Svn from /usr/bin/git to /usr/local/bin/git and then restart RStudio.

**Comment by sandan** [comment]
I was following this guide: http://r-pkgs.had.co.nz/git.html#git-init. I got stuck on the part after 

> In a shell, run git init. Restart RStudio and reopen your package.

I couldn't see the git pane right away. I had to go to View->Show Git

**Comment by GershTri** [comment]
Same problem. Solved it using two methods: 

1. By using `/usr/local/git/bin/git`. For some reason `/usr/local/bin/git` (mentioned by @joebowness ) is just a shortcut to `/usr/local/git/bin/git`, and `usr/bin/git`, despite pointing to what appears to be a git executable, doesn't work at all (without xcode, see #2).
2. By installing xcode and confirming with username and password. In this case `usr/bin/git` is the the exec being used by rstudio.

Is it odd that there are multiple git execs in subdirectories of the same directory? One of them, `/usr/local/git/bin/git`, the one that works without xcode, was created precisely one year ago and is thus older than the other, `usr/bin/git`, which was created in July and only works with xcode.

**Comment by jennybc** [comment]
@GershTri It's hard to say exactly how you got into this state. How did you install git one year ago? The simplest way I know to get Git working on Mac OS and with RStudio is definitely via Xcode command line tools. Which seems to be where you've ended up. And, yes, there have been combinations of Mac OS and RStudio versions where *only* the Xcode-managed version of Git would actually work (although I believe that is not the current situation).

**Comment by GershTri** [comment]
I wasn't aware that git was already installed on macs, so I installed it myself. Usually apps recognize other versions of themselves during installation, which is why I'm a little perplexed by my labyrinthine usr/ directory. Installing Xcode is definitely the easiest method to get things working, but you end up with an app that you will probably never use parked on nearly 6 GB of valuable hard drive real estate. It seems like there should be a better way.

**Comment by jennybc** [comment]
I recommend installing just the *Xcode command line tools*:

http://happygitwithr.com/install-git.html#mac-os

Based on your 6 GB comment, I wonder if we're miscommunicating and you installed Xcode in its entirety ... although I admit I don't know the size of Xcode command line tools. In that same section are ways to install Git that are more surgical, but not as easy.

**Comment by GershTri** [comment]
You're right. I just uninstalled Xcode (which is actually almost 11 GB). The git pane in Rstudio disappeared. Then I installed the command line tools using `xcode-select --install`, restarted R and… voilá! Everything seems to be working now. Thanks!

**Comment by sanity4sale** [comment]
Thank you so much, these instructions helped me reinstall Git for RStudio!!!

**Comment by jmuhlenkamp** [comment]
+1

**Comment by critgeog** [comment]
thank you all!

**Comment by jennybc** [comment]
For those of you helped by this thread ... is there one or two tips that constitute the "bottom line" and that should be incorporated into the instructions?

I'm having a hard time determining if there is an action item for me and would appreciate such a summary.

**Comment by critgeog** [comment]
I updated R, RStudio, and OS to HighSierra. 

xcode-select --install . I launched it in the App Store, re-installed xcode (I think as a result of HighSierra). Then I agreed to terms in shell. Next, I restarted R, created a project, and was able to enter git info.

**Comment by jmuhlenkamp** [comment]
All I did was `xcode-select --install` and then re-open my Rstudio Projects and they were all fixed.

**Comment by harshmisra-1** [comment]
> I had this same problem even after installing XCode and the command line tools. It was fixed after I ran a simple command in the terminal like `git config --global --list` which then forced me to agree to the XCode license agreement. Then, restarted RStudio and it recognized that git was on my system.

@nickreich : AMazing Reply, that did help

**Comment by rupertoverall** [comment]
> > I had this same problem even after installing XCode and the command line tools. It was fixed after I ran a simple command in the terminal like `git config --global --list` which then forced me to agree to the XCode license agreement. Then, restarted RStudio and it recognized that git was on my system.
> 
> @nickreich : AMazing Reply, that did help

This worked for me too after RStudio suddenly stopped showing git tools. XCode is often updated in the background and breaks things like this silently.

**Comment by kevinushey** [comment]
There have been a couple Xcode updates released recently, so I expect users will be bumping into this again. We're planning to report this state more clearly in the IDE:

https://github.com/rstudio/rstudio/pull/5494

but that won't become part of an official RStudio release for a little while yet.

Until then, executing:

```
sudo xcode-select --install
/usr/bin/git --version
```

in a terminal should be sufficient to see whether Apple wants you to agree to the Xcode license or install command line tools.

**Comment by phsemple** [comment]
Same problem for me in 2020: Had to browse into /usr/bin/git and step back to /usr/local/bin/git for the git. The svm path was correct.

**From CMartin in 2016:** I was also stumped by the RStudio git binary picker which looked correct at /usr/bin/git, but my actual git installation was at /usr/local/bin/git (as found with the which git command). Once I pointed RStudio to the correct git binary location, everything reappeared.

**Comment by dkori** [comment]
> Same problem for me in 2020: Had to browse into /usr/bin/git and step back to /usr/local/bin/git for the git. The svm path was correct.
> 
> **From CMartin in 2016:** I was also stumped by the RStudio git binary picker which looked correct at /usr/bin/git, but my actual git installation was at /usr/local/bin/git (as found with the which git command). Once I pointed RStudio to the correct git binary location, everything reappeared.

Just had the same issue, git disappeared from Rstudio out of nowhere shortly after I successfully cloned a repo using Rstudio. Changing the  path to the git installation from "usr/bin/git" to "usr/local/bin/git" as you described fixed it for me as well.

**Comment by baderstine** [comment]
This turned out to be the problem: 

> I wonder if Mike and Natalia are able to run `/usr/bin/git --version` successfully? Maybe RStudio is inadvertently trying to use the version of `git` at `/usr/bin/git`, but that is failing for some reason (e.g. missing developer tools, borked system `git` installation for other reasons)?

Running this (`/usr/bin/git --version`) returned the message: "You have not agreed to the Xcode license agreements.  blah blah..."  Often happens after updating Xcode.

I had to run `sudo xcodebuild -license` and agree to the licenses.  Following that, restarted RStudio and created a New Project in an Existing Directory (that had already been initialized as a git repo) and the Git tab showed up.

**Comment by letgenelhu** [comment]
`xcode-select --install` worked perfectly. I think maybe the macOS update triggered it.

**Comment by paulotimi** [comment]
> sudo xcode-select --install
> /usr/bin/git --version

Hello, I am new here.
i tried changing my Git executable pathway but i couldn't locate usr/local/bin/git on my MacBook. I tried copying and pasting this but the pathway is uneditable. How can i solve this please?

**Comment by sanjmeh** [comment]
> You're right. I just uninstalled Xcode (which is actually almost 11 GB). The git pane in Rstudio disappeared. Then I installed the command line tools using `xcode-select --install`, restarted R and… voilá! Everything seems to be working now. Thanks!

This looks to be a very long drawn solution. Is this the final and only solution? I am stuck with the same problem that rstudio does not detect git while if I go to a mac terminal or rstudio terminal pane we can execute git commands.

**Comment by jennybc** [comment]
@sanjmeh In one of the places where git works, do `which git` to reveal where the executable lives. Then tell RStudio about that path in *Tools > Global options > Git/SVN*. At least, that's a sketch of a solution.
