### ISSUE TITLE
tilde troubles

### ISSUE THREAD

**Issue by karlp-asrs** [jennybc/happy-git-with-r#86]
I am working with a new Windows surface computer.  Fresh out of the box, setup with default settings.
Installed R, Rstudio and Git, again all default settings.

Then tried working through the example in chapter 6 new project, github first.  I made a test respository on github.  Then went to Create Project in Rstudio.  I copied the URL in to Repository URL but didn't make any changes to the "Create project as subdirectory of::" box.  This default setting in this box is "~".  Somehow or other my Sys.getenv("HOME") on this computer points to a document folder in my OneDrive account.

Meanwhile, Git Bash thinks "~" means "c:/users/karlp" and that's where it installed my gitconfig file.  

This lead to no good.  Weird and unhelpful error messages and no results.  

I finally noticed the actual directory location of the project folder.  I started over and created the project at "c:/users/karlp" and everything works as it should.

Wasted a lot of time on this, but did end up reading your whole guide from the beginning and learned the word "bullshittery", so it wasn't a complete loss.

**Comment by jennybc** [comment]
Yeah, I've written everything I know about this here:

http://happygitwithr.com/ssh-keys.html#git2r-or-some-other-tool-cant-find-ssh-keys-on-windows

It is yet another example of Windows being a rather miserable OS for this sort of work. Basically "user's home directory" is not well-defined.

**Comment by jennybc** [comment]
I'd welcome any sort of specific feedback or PR that might tip off future Windows users in the specific workflow you were following.

**Comment by karlp-asrs** [comment]
thanks for the immediate response.  Your book is very helpful, especially when you read it.  My workflow was to jump to the chapter that addressed what I wanted to do and skip the beginning -- when I read from the beginning, it made more sense and eventually the light bulb went on.  

Nice work -- impressive how you make what has great potential to be very boring into an entertaining read.

**Comment by jennybc** [comment]
Thanks!

Well, this Windows home directory gotcha is buried in the SSH troubleshooting section and perhaps should be somewhere more visible.
