### ISSUE TITLE
Command Prompt open in R instead of Bash

### ISSUE THREAD

**Issue by nicolehardy87** [jennybc/happy-git-with-r#89]
I'm running windows 10 with the newest version of both R and Rstudio. 

I went to Tools > Shell to open the git bash and the command prompt opens. The box that says “Use Git Bash as shell for Git projects” is checked, but bash never opens. it is always the command prompt. 

Any suggestions?

**Comment by nicolehardy87** [comment]
Hi Joey,

Thanks so much for your reply. I did install git for windows and followed all the instructions on the page and got the correct results according to the tutorial. However when I try and access the shell from Rstudio I get the command prompt and not bash although I have successfully installed git and completed the tutorial by simply searching my computer and opening bash myself. 

Hopefully this makes more sense. 

Sincerely,

Nicole

**Comment by jpheffne** [comment]
Hi Nicole, 

Have you tried going into RStudio's "Tools/Global Options/Terminal" settings? Once I downloaded Git for Windows then that appeared as an option in the "new terminals open with ..." setting. If it still doesn't appear, I think that Happy Git tutorial has some troubleshooting for connecting RStudio to Git but I also just started this tutorial so don't know much myself. 

Best,
Joey

**Comment by jennybc** [comment]
I don't use Windows as my primary OS but do test these instructions whenever I can. Obviously, I get more chances to test usage than initial setup.

But these instructions were constructed very deliberately:

http://happygitwithr.com/install-git.html#install-git-windows

especially this bit:

> **NOTE**: Select “Use Git from the Windows Command Prompt” during installation.

I imagine you should also restart RStudio after this, for good measure.

@nicolehardy87 Perhaps you already did all this, but thought I'd emphasize it just in case. Let us know how it's going. I like to keep these instructions as current and completely as possible.
